[package]
name = "rz-vrf"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
rz-ecvrf = { path = "../../rz-ecvrf" }
risc0-zkvm = { version = "1.1.3", default-features = false, features = ['std'] }
