[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { workspace = true }
rz-ecvrf = { workspace = true }
risc0-zkvm = { version = "2.1.0" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
libecvrf = { version = "1.2.1-beta.0" }
